### PR TITLE
Add support for SUSE SLE12

### PR DESCRIPTION
**Pull request by jwennerberg**

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@jwennerberg Thanks!

I don't have ready access to Suse 12. Has this code been tested on that platform?

**Comment by ghoneycutt** [comment]
@Phil-Friderici You have any Suse 12 systems around by chance?

**Comment by ghoneycutt** [comment]
The metadata.json and README also need to be updated. I can do that, just a note so I don't forget.

**Comment by Phil-Friderici** [comment]
@ghoneycutt I'll ask our Suse 12 testing specialists to help us.

**Comment by ofsole** [comment]
Hey guys, I tested this module on our SLES12 servers, it works great, in addition, there may be one line could be updated, you can check the link here:
https://github.com/jwennerberg/puppet-module-nscd/blob/sle12/manifests/init.pp#L172

**Comment by jwennerberg** [comment]
@anders-larsson Did you have a chance to test this?

**Comment by Phil-Friderici** [comment]
@ofsole Thanks a lot for testing and the additional hint :)

**Comment by ghoneycutt** [comment]
Thanks @jwennerberg @Phil-Friderici @ofsole !!

Could you please squash this commits and I'll get them merged

**Comment by jwennerberg** [comment]
Done! =)

**Comment by ghoneycutt** [comment]
Released in v1.4.0

Thanks everyone!!

**Pull request merged**
