### PR TITLE
Add rubocop support to lint spec tests and make recommended changes

### PR DESCRIPTION
**Pull request by ghoneycutt**

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
@ghoneycutt that looks very interesting. Only drawback is that the tests runs much longer with rubycop :(

**Comment by ghoneycutt** [comment]
@Phil-Friderici Seems about the same as this test which was pre-rubocop 

https://travis-ci.org/ghoneycutt/puppet-module-nscd/builds/86252151

The rubocop test run itself runs very fast and is only done with the newest puppet version of each ruby version (except 1.8.7)

Am I missing something?

**Comment by ghoneycutt** [comment]
If nothing else, this taught me about using `%r{/foo/bar}` instead of `/\/foo\/bar/` :)

**Comment by Phil-Friderici** [comment]
Now that I have used rubocop more often I am starting to like it. It actualy helps to find errors and enhance style.

Do you think this is something to get mandatory (activated at Travis) at a later point ?

**Comment by ghoneycutt** [comment]
Already is :)

https://github.com/ghoneycutt/puppet-module-nscd/blob/master/.travis.yml#L25

**Pull request merged**
