### PR TITLE
Support el8

### PR DESCRIPTION
**Pull request by anders-larsson**
First commit is to ensure spec tests continue to work for ruby 2.1.9.

Adds support for EL8-based distributions.

### CODE REVIEW

**Comment by anders-larsson** [comment]
Oops. I had totally missed #68. Well now you have two pull requests for EL8 @ghoneycutt.

Thanks for your work.

**Comment by ghoneycutt** [comment]
Is nscd even used on EL8? I thought it was deprecated in EL7 in favor of sssd.

**Comment by anders-larsson** [comment]
Hm. Yes it appears that they think sssd and nscd might duplicate caching functionality. I do think it serves a purpose though when used in combination with other applications.

**Comment by anders-larsson** [comment]
How would you like us to proceed with this pull request?

Thanks and Best Regards,

**Comment by braddeicide** [comment]
In the Redhat documentation they say not to use nscd and sssd together for passwd, group, services and in 8 they say sssd is enabled by default.  I don't see any solution other than nscd for hosts however.  I believe nscd should work with redhat/centos 8 however only hosts should be enabled by default (at all really)

enable-cache hosts yes
enable-cache passwd no
enable-cache group no
enable-cache netgroup no
enable-cache services no

**Comment by anders-larsson** [comment]
Hi @braddeicide,

Thank you for your contribution. It has been merged. I did change the commit message a bit though. I hope it is OK.

**Comment by ghoneycutt** [comment]
Thanks everyone!!

**Comment by ghoneycutt** [comment]
Released in 1.14.0

**Pull request merged**
