### PR TITLE
Add support for EL9

### PR DESCRIPTION
**Pull request by anders-larsson**
passwd, group, hosts, services and netgroup enabled by default (as it is in the provided RPM in EL9).

Spec tests are not yet tested. Need to setup a testing setup since container is not present yet and PDK is not yet used for this module.

Result looks good on a actual system though.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Great work @anders-larsson ! Needs the README updated - https://github.com/ghoneycutt/puppet-module-nscd#compatibility

**Comment by ghoneycutt** [comment]
Tests pass

**Comment by anders-larsson** [comment]
Removed `WIP` tag.

**Comment by anders-larsson** [comment]
Can you have a look @ghoneycutt ? Thanks!

**Comment by anders-larsson** [comment]
Removed "WIP" from commit message.

**Comment by ghoneycutt** [comment]
Replaced by #74 and #78

**Comment by ghoneycutt** [comment]
Released in 2.1.0

**Pull request closed without merging**
