### PR TITLE
re-rebase solaris support

### PR DESCRIPTION
**Pull request by Phil-Friderici**
successor of https://github.com/ghoneycutt/puppet-module-nscd/pull/36

### CODE REVIEW

**Comment by Phil-Friderici** [comment]
If Travis can agree, this would be done now :)

**Comment by Phil-Friderici** [comment]
As Travis didn't found any problems, this is good to be merged in my eyes.

**Comment by ghoneycutt** [comment]
Whew! Glad to see that one merged! Thanks a ton.

Released in v1.7.0

**Comment by Phil-Friderici** [comment]
Yes, finally :)

Now it's time for beautification. You'll get a patch to remove the empty lines in nscd.conf soon.

**Pull request merged**
